# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-ISBN-LibUniverIt-Driver
version:      0.1
version_from: lib/WWW/Scraper/ISBN/LibUniverIt/Driver.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
